import mongoose from "mongoose"
import { Schema } from "mongoose"

const appointmentSchema = new mongoose.Schema({
           
    userId:{
        type:String,
        required:true
    },
    docId:{
        type:String,
        required:true
    },
    slotDate:{
        type:String,
        required:true
    },
    slotTime:{
        type:String,
        required:true
    },
    userData:{
        type:Object,
        required:true
    },
    docData:{
        type:String,
        required:true
    },
    amount:{
        type:Number,
        required:true
    },
    date:{
        type:Number,
        required:true
    },
    cancelled:{
        type:Boolean,
        default:false
    },
    payment:{
        type:Boolean,
        default:false
    },
    paymentId:{
        type:String,
        default:null
    },
    isCompleted:{
        type:Boolean,
        default:false
    },
    checkupReport:{
        type:Object,
        default:null
    },
    consultationType:{
        type:String,
        enum:['online','offline'],
        default:'offline'
    },
    videoCallId:{
        type:String,
        default:null
    },
    videoCallLink:{
        type:String,
        default:null
    },
    videoCallStatus:{
        type:String,
        enum:['pending','active','ended'],
        default:'pending'
    },
    refundId:{
        type:String,
        default:null
    },
    refundStatus:{
        type:String,
        enum:['none','initiated','processed','failed'],
        default:'none'
    },
    refundAmount:{
        type:Number,
        default:0
    }

})
const Appointment = mongoose.model("Appointment",appointmentSchema)
export default Appointment